### ISSUE TITLE
ofBuffer.getData() not a valid method for latest stable version (0.8.4)

### ISSUE THREAD

**Issue by occak** [trentbrooks/ofxPocoNetwork#1]
I wish to use this with the latest stable version (0.8.4) but getData mentioned in the SocketConnectionHandler, ReactorClient, ReactorServer, TCPClient and possibly other cpp files is valid for master only. Is there a way I can get around this within the stable version?

**Comment by trentbrooks** [comment]
It's up to date with master, not the stable 084 unfortunately. But I do have a working version for 084 that i pushed to a different branch- https://github.com/trentbrooks/ofxPocoNetwork/tree/084

The only change is all the newer ofBuffer.getData() methods have been changed to the 084 compatible ofBuffer.getBinaryBuffer().
