### ISSUE TITLE
delimiter should be user-settable for FRAME_DELIMITER

### ISSUE THREAD

**Issue by jweather** [trentbrooks/ofxPocoNetwork#4]

**Comment by trentbrooks** [comment]
It should be? https://github.com/trentbrooks/ofxPocoNetwork/blob/master/libs/PocoTCP/SocketConnectionHandler.cpp#L153

**Comment by jweather** [comment]
How do I set that when using TCPClient?

**Comment by trentbrooks** [comment]
A direct call after connect should work, not an ideal solution as it requires the socket connection to succeed before calling.
client.connect("localhost", 12345, ofxPocoNetwork::TYPE_DELIMITED);
client.socketHandler->setDelimiter(",");

**Comment by jweather** [comment]
Got it, thanks.
